//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EventViewer.rc
//
#define IDCANCEL2                       3
#define ID_APPLY                        3
#define IDOK2                           4
#define ID_CLEAR_FILTERS                4
#define ID_DEFAULT_FILTER               4
#define IDM_ABOUTBOX                    0x0010
#define IDD_EVENTVIEWER_DIALOG          102
#define IDC_PROGRESS                    102
#define IDC_PRINT                       106
#define IDC_EXPORT                      107
#define IDC_PREVIOUS                    108
#define IDC_NEXT                        109
#define IDC_VIEW_INCIDENTS              110
#define IDC_ALARM_MANAGER               111
#define ID_INDICATOR_CAP                112
#define IDR_MAINFRAME                   128
#define IDR_EV_MAIN_MENU                129
#define IDI_REFRESH                     130
#define IDI_REFRESH_HOT                 133
#define IDI_PRINT_HOT                   136
#define IDI_PRINT                       137
#define IDI_SAVE_HOT                    138
#define IDI_SAVE                        139
#define IDI_FILTERS                     140
#define IDI_FILTERS_HOT                 141
#define IDI_NEXT                        142
#define IDI_PREVIOUS_HOT                143
#define IDI_PREVIOUS                    145
#define IDI_NEXT_HOT                    146
#define IDI_UPDATING                    147
#define IDI_UPDATING_HOT                148
#define ID_NAMED_FILTER_COMBO           149
#define ID_EVENT_LEVEL_COMBO            150
#define IDI_INCIDENT_HOT                151
#define IDI_INCIDENT                    152
#define IDD_MULTIPLE_LOAD               155
#define IDD_DIALOG1                     156
#define IDD_AUDIT_EVENT_FILTER1         156
#define IDD_AUDIT_EVENT_FILTER          156
#define IDR_AUDIT_COLUMNS               157
#define IDD_DATA_POINT_EVENT_FILTER     157
#define IDR_DATAPOINT_COLUMNS           158
#define IDD_WAIT_FOR_CLOSE              158
#define IDB_CAP_ACTIVE                  160
#define IDI_CAP_ACTIVE                  161
#define IDR_COMBINED_EVENT_COLUMNS      162
#define IDD_COMBINED_EVENT_FILTER       163
#define IDI_PAGE_UP                     164
#define IDI_PAGE_DOWN                   165
#define IDI_ALARMMANAGER_HOT            167
#define IDI_ALARMMANAGER                168
#define IDD_SHOW_COMMENT                169
#define IDD_FILTER_NAME                 170
#define IDC_SUBSYSTEM                   1000
#define IDC_PAGER_CTRL                  1001
#define IDC_EVENTS_TBAR                 1002
#define IDC_EVENT_LIST                  1002
#define IDC_SUBSYSTEM_EXT               1003
#define IDC_LOCATION                    1004
#define IDC_LOCATION_EX                 1005
#define IDC_FROM_DATE                   1006
#define IDC_FROM_TIME                   1007
#define IDC_TO_DATE                     1008
#define IDC_TO_TIME                     1009
#define IDC_LOAD_LIST                   1010
#define IDC_OPERATOR_EXT                1010
#define IDC_MENU_LINE                   1011
#define IDC_EVENTTYPE_EXT               1011
#define IDC_ASSET                       1012
#define IDC_ALARM_ID                    1013
#define IDC_VALUE                       1013
#define IDC_ASSET2                      1013
#define IDC_DESC                        1013
#define IDC_DESCRIPTION                 1014
#define IDC_STATUS                      1014
#define IDC_DISPLAY_VALUE               1014
#define IDC_ALARMTYPE_EXT               1015
#define IDC_SAVE                        1017
#define IDC_BUTTON1                     1018
#define IDC_PAGE_UP                     1018
#define IDC_BUTTON_SAVEFILTER           1018
#define IDC_URGENT                      1019
#define IDC_PAGE_DOWN                   1019
#define IDC_BUTTON_DELETEFILTER         1019
#define IDC_CRITICAL                    1020
#define IDC_LIST_PLACEHOLDER            1020
#define IDC_MAJOR                       1021
#define IDC_FROM                        1021
#define IDC_MINOR                       1022
#define IDC_EDIT_ALARM_COMMENT          1022
#define IDC_EVENT                       1023
#define IDC_COMBO_NAMEDFILTER           1023
#define IDC_EDIT_FILTER_NAME            1024
#define IDC_STATIC_SEVERITY             1025
#define IDC_OPERATOR                    1054
#define IDC_SEVERITY                    1055
#define IDC_SEVERITY_old                1055
#define IDC_EVENT_TYPE                  1056
#define IDC_ALARM_TYPE                  1057
#define IDC_CURRENT                     1062
#define ID_FILE_EXIT                    32772
#define IDC_VIEW_FILTERS                32774
#define ID_VIEW_TOOLBARS_STATUSBAR      32777
#define ID_VIEW_TOOLBARS_TOOLBAR        32778
#define ID_COLUMNS_SOURCETIMESTAMP      32780
#define ID_COLUMNS_DESCRIPTION          32781
#define ID_COLUMNS_EVENT_TYPE           32782
#define ID_COLUMNS_ASSET                32783
#define ID_COLUMNS_OPERATOR             32784
#define ID_COLUMNS_SEVERITY             32785
#define ID_COLUMNS_SUBSYSTEM            32786
#define ID_COLUMNS_LOCATION             32787
#define ID_COLUMNS_TRANSACTIVETIMESTAMP 32788
#define IDC_LOAD_AUDIT_FILTER           32789
#define IDC_LOAD_DATAPOINT_FILTER       32790
#define ID_COLUMNS_VALUE                32791
#define ID_COLUMNS_STATUS               32792
#define IDC_COLUMNS                     32793
#define IDC_STATUS_BAR                  32794
#define IDC_TOOL_BAR                    32795
#define IDC_SEVERITY_LIST               32797
#define ID_COLUMNS_DATETIME             32798
#define ID_COLUMNS_MMS                  32803
#define ID_COLUMNS_DSS                  32804
#define ID_COLUMNS_AVL                  32805
#define ID_COLUMNS_COMMENT              32807
#define IDC_SHOW_ALL                    32809
#define ID_INDICATOR_SIZE               59142
#define ID_FILE_EXPORT                  59143
#define ID_TEST                         61190
#define ID_SYS_EXIT                     61190

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         1026
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
