#pragma once

#define PARAM_INTERNAL			_T("INTERNAL")
#define PARAM_RUN_SILENT		_T("SILENT")
#define PARAM_OUTPUT_RC			_T("RC_PATH")
#define PARAM_OUTPUT_LANG		_T("OUTPUT_LANG")
#define PARAM_OUTPUT_ENA		_T("OUTPUT_ENA")
#define PARAM_LIBRARY_PATH		_T("LIBRARY_PATH")
#define PARAM_RESOURCE_SRC_PATH	_T("SOURCE_PATH")
#define PARAM_OVERRIDE_LCID		_T("OVERRIDE_LCID")
#define PARAM_NARROW_OUTPUT		_T("NARROW_OUTPUT")
