//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SystemManager.rc
//
#define IDS_ABOUTBOX                    101
#define IDD_SYSTEMMANAGER_DIALOG        102
#define IDR_MAINFRAME                   128
#define IDR_CONTEXT_MENU                129
#define IDD_STARTPROCESS_DIALOG         131
#define IDD_LOGIN_DIALOG                132
#define IDD_OPTIONS_DIALOG              133
#define IDD_STOPPROCESS_DIALOG          135
#define IDD_SHUTDOWN_MONITOR_DIALOG     136
#define IDD_PROCESS_PARAMS              144
#define IDD_CHANGEOPERATIONMODE_DIALOG  148
#define IDR_MAINMENU                    149
#define IDR_TOOLBAR1                    160
#define IDB_UP                          166
#define IDB_DOWN                        167
#define IDD_SYSTEMCONTROLLER_DIALOG     169
#define IDI_ICON1                       300
#define IDI_ICON2                       301
#define IDC_MENU_LINE                   437
#define IDC_MAIN_PROCESSLIST            1000
#define IDC_LOGIN                       1001
#define IDC_START                       1002
#define IDC_STOP                        1003
#define IDC_SHUTDOWN                    1004
#define IDC_REFRESH                     1005
#define IDC_LOGOUT                      1008
#define IDC_OPTIONS                     1010
#define IDC_STATUS                      1012
#define IDC_STATIC_PASSWORD             1016
#define IDC_STATIC_USERNAME             1017
#define IDC_USERNAME_EDIT               1018
#define IDC_REFRESH_RATE_COMBO          1019
#define IDC_DEBUG_LEVEL_COMBO           1020
#define IDC_STATIC_PORT_NUMBER          1021
#define IDC_CONTROL                     1023
#define IDC_MONITOR                     1024
#define IDD_STOP_LISTPROCESSES          1025
#define IDC_STOP_STATIC                 1026
#define IDC_START_CONTROL               1027
#define IDC_START_MONITOR               1028
#define IDC_PROCESSLIST                 1030
#define IDC_PROCESSES                   1031
#define IDC_HOSTNAME                    1032
#define IDC_STOP_PROCESS_LIST           1035
#define IDC_MODE_PROCESS_LIST           1037
#define IDC_START_PROCESS_LIST          1038
#define IDC_NAME_COMBO                  5027
#define IDC_PROFILE_COMBO               5028
#define IDC_LOCATION_COMBO              5029
#define IDC_PASSWORD_EDIT               5030
#define IDC_HOST_NAME                   6000
#define IDC_PORT_NUMBER                 6001
#define IDC_HOST_NAME_EDIT              6002
#define IDM_START_PROCESS               32780
#define IDM_STOP_PROCESS                32781
#define IDM_SHUTDOWN_MONITOR            32782
#define IDM_VIEW_MONITOR                32783
#define IDM_PROCESS_PARAM               32786
#define ID_FILE_LOGIN                   32787
#define ID_FILE_LOGOUT                  32788
#define ID_FILE_OPTIONS                 32789
#define ID_FILE_EXIT                    32790
#define IDM_CHANGEOPERATIONMODE         32791
#define ID_VIEW_REFRESH                 32796
#define ID_VIEW_SYSTEMCONTROLLERS       32797
#define ID_VIEW_OPTIONS                 32798
#define ID_CONTROL_STARTPROCESS         32799
#define ID_CONTROL_STOPPROCESS          32800
#define ID_CONTROL_CHANGEPROCESSOPERATIONMODE 32801
#define ID_CONTROL_SHUTDOWNSYSTEMCONTROLLER 32802
#define ID_HELP_SYSTEMMANAGERHELP       32803
#define ID_HELP_ABOUT                   32804
#define ID_BUTTON_LOGIN                 32820
#define ID_BUTTON_LOGOUT                32821
#define ID_BUTTON_START                 32822
#define ID_BUTTON_STOP                  32823
#define ID_BUTTON_REFRESH               32824
#define ID_CONTROL_SETPARAM             32825
#define IDS_LOGOUT                      32825
#define IDS_EXIT                        32826
#define IDS_ALL_FUNCTIONALITIES         32827
#define IDS_LOGIN                       32828
#define IDS_INVALID_USER                32829
#define IDS_INVALID_PASSWORD            32830
#define IDS_INVALID_PROFILE             32831
#define IDS_INVALID_LOCATION            32832
#define IDS_INVALID_WORKSTATION         32833
#define IDS_INVALID_PROFILE_NOT_PERMITTED 32834
#define IDS_PROFILE_NOT_PERMITTED       32834
#define IDS_LOCATION_NOT_PERMITTED      32835
#define IDS_UNIDENTIFIED_CONSOLE        32836
#define IDS_AUTHENTICATION_SERVICE_ERROR 32837
#define IDS_CANNOT_ACCESS_SYSTEM_CONTROLLER 32838
#define IDS_NO_SYSTEM_CONTROLLER        32839
#define IDS_CANNOT_RETRIEVE_INFO        32840
#define IDS_DATABASE_ERROR              32841
#define IDS_PORT_NUMBER                 32842
#define IDS_ALL_FUNCTIONALITY           32843
#define IDS_UNKNOWN_ERROR               32844
#define IDS_START_PROCESS               32845
#define IDS_STOP_PROCESS                32846
#define IDS_PROCESS_PARAM_ALLOWED       32847
#define IDS_SHUT_DOWN                   32848
#define IDS_SET_OPERATING_MODE          32849
#define IDS_SET_OPTIONS                 32850

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        171
#define _APS_NEXT_COMMAND_VALUE         32826
#define _APS_NEXT_CONTROL_VALUE         1041
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
