// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __IDllHostCorbaDef_hh__
#define __IDllHostCorbaDef_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_IDllHostCorbaDef
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_IDllHostCorbaDef
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_IDllHostCorbaDef
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE TA_Base_Core

_CORBA_MODULE_BEG

#ifndef __TA__Base__Core_mIDllHostCorbaDef__
#define __TA__Base__Core_mIDllHostCorbaDef__

  class IDllHostCorbaDef;
  class _objref_IDllHostCorbaDef;
  class _impl_IDllHostCorbaDef;
  
  typedef _objref_IDllHostCorbaDef* IDllHostCorbaDef_ptr;
  typedef IDllHostCorbaDef_ptr IDllHostCorbaDefRef;

  class IDllHostCorbaDef_Helper {
  public:
    typedef IDllHostCorbaDef_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_IDllHostCorbaDef, IDllHostCorbaDef_Helper> IDllHostCorbaDef_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_IDllHostCorbaDef,IDllHostCorbaDef_Helper > IDllHostCorbaDef_out;

#endif

  // interface IDllHostCorbaDef
  class IDllHostCorbaDef {
  public:
    // Declarations for this interface type.
    typedef IDllHostCorbaDef_ptr _ptr_type;
    typedef IDllHostCorbaDef_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    class NameNotFound : public ::CORBA::UserException {
    public:
      
      

      inline NameNotFound() {
        pd_insertToAnyFn    = insertToAnyFn;
        pd_insertToAnyFnNCP = insertToAnyFnNCP;
      }
      NameNotFound(const NameNotFound&);
      
      NameNotFound& operator=(const NameNotFound&);
      virtual ~NameNotFound();
      virtual void _raise() const;
      static NameNotFound* _downcast(::CORBA::Exception*);
      static const NameNotFound* _downcast(const ::CORBA::Exception*);
      static inline NameNotFound* _narrow(::CORBA::Exception* _e) {
        return _downcast(_e);
      }
      
      inline void operator>>=(cdrStream&) const { }
      inline void operator<<=(cdrStream&) { }

      static _core_attr insertExceptionToAny    insertToAnyFn;
      static _core_attr insertExceptionToAnyNCP insertToAnyFnNCP;

      virtual ::CORBA::Exception* _NP_duplicate() const;

      static _core_attr const char* _PD_repoId;
      static _core_attr const char* _PD_typeId;

    private:
      virtual const char* _NP_typeId() const;
      virtual const char* _NP_repoId(int*) const;
      virtual void _NP_marshal(cdrStream&) const;
    };

    static _dyn_attr const ::CORBA::TypeCode_ptr _tc_NameNotFound;

  
  };

  class _objref_IDllHostCorbaDef :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    ::CORBA::Object_ptr getObject(const char* objectName);

    inline _objref_IDllHostCorbaDef()  { _PR_setobj(0); }  // nil
    _objref_IDllHostCorbaDef(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_IDllHostCorbaDef();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_IDllHostCorbaDef(const _objref_IDllHostCorbaDef&);
    _objref_IDllHostCorbaDef& operator = (const _objref_IDllHostCorbaDef&);
    // not implemented

    friend class IDllHostCorbaDef;
  };

  class _pof_IDllHostCorbaDef : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_IDllHostCorbaDef() : _OMNI_NS(proxyObjectFactory)(IDllHostCorbaDef::_PD_repoId) {}
    virtual ~_pof_IDllHostCorbaDef();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_IDllHostCorbaDef :
    public virtual omniServant
  {
  public:
    virtual ~_impl_IDllHostCorbaDef();

    virtual ::CORBA::Object_ptr getObject(const char* objectName) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_IDllHostCorbaDef;

_CORBA_MODULE_END



_CORBA_MODULE POA_TA_Base_Core
_CORBA_MODULE_BEG

  class IDllHostCorbaDef :
    public virtual TA_Base_Core::_impl_IDllHostCorbaDef,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~IDllHostCorbaDef();

    inline ::TA_Base_Core::IDllHostCorbaDef_ptr _this() {
      return (::TA_Base_Core::IDllHostCorbaDef_ptr) _do_this(::TA_Base_Core::IDllHostCorbaDef::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_TA_Base_Core
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, const TA_Base_Core::IDllHostCorbaDef::NameNotFound& _s);
void operator<<=(::CORBA::Any& _a, const TA_Base_Core::IDllHostCorbaDef::NameNotFound* _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const TA_Base_Core::IDllHostCorbaDef::NameNotFound*& _sp);

void operator<<=(::CORBA::Any& _a, TA_Base_Core::IDllHostCorbaDef_ptr _s);
void operator<<=(::CORBA::Any& _a, TA_Base_Core::IDllHostCorbaDef_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, TA_Base_Core::IDllHostCorbaDef_ptr& _s);



inline void
TA_Base_Core::IDllHostCorbaDef::_marshalObjRef(::TA_Base_Core::IDllHostCorbaDef_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_IDllHostCorbaDef
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_IDllHostCorbaDef
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_IDllHostCorbaDef
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_IDllHostCorbaDef
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_IDllHostCorbaDef
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_IDllHostCorbaDef
#endif

#endif  // __IDllHostCorbaDef_hh__

