/**
  * The source code in this file is the property of
  * Ripple Systems and is not for redistribution
  * in any form.
  *
  * Source:   $File: //depot/TA_Common_V1_TIP/transactive/core/process_management/IDL/src/IProcessObserverCorbaDef.idl $
  * @author:  Justin Ebedes
  * @version: $Revision: #1 $
  *
  * Last modification: $DateTime: 2015/01/19 17:43:23 $
  * Last modified by:  $Author: CM $
  *
  * This interface is implemented by classes wishing to be
  * notified when process data on a System Controller
  * is changed.
  *
  */

#ifndef IPROCESSOBSERVERCORBADEF_IDL_INCLUDED
#define IPROCESSOBSERVERCORBADEF_IDL_INCLUDED

#include "core/process_management/IDL/src/ProcessManagementDataDefinitionsCorbaDef.idl"
#include "core/process_management/IDL/src/IProcessManagerCorbaDef.idl"

module TA_Base_Core
{
        interface IProcessObserverCorbaDef : IProcessManagerCorbaDef
        {
			/**
			  * notifyProcessData
			  *
			  * Called by a subject to notify an observer that 
			  * process data has changed.
			  */
			void notifyProcessData(in ProcessData p_processData);
        };
};

#endif // IPROCESSOBSERVERCORBADEF_IDL_INCLUDED

