//
// The source code in this file is the property of
// Ripple Systems and is not for redistribution
// in any form.
//
// Source:   $File: //depot/TA_Common_V1_TIP/transactive/bus/security/duty_agent/IDL/src/IDutyAgentQueryCorbaDef.idl $
// @author:  Gregg Kirkpatrick
// @version: $Revision: #1 $
//
// Last modification: $DateTime: 2015/01/19 17:43:23 $
// Last modified by:  $Author: CM $
//
// Duty Agent IDL interface for duty queries.
//

#ifndef IDUTYAGENTQUERYCORBADEF_H_INCLUDED
#define IDUTYAGENTQUERYCORBADEF_H_INCLUDED

#include <core/exceptions/IDL/src/CommonExceptionsCorbaDef.idl>
#include <bus/security/duty_agent/IDL/src/DutyAgentTypeCorbaDef.idl>
#include <bus/security/authentication_agent/IDL/src/IAuthenticationAgentCorbaDef.idl>

module TA_Base_Bus
{
	interface IDutyAgentQueryCorbaDef
	{
		// Called by Rights Agents
		boolean queryHasDuty( in TA_Base_Bus::IAuthenticationAgentCorbaDef::SessionInfoCorbaDef session, in DutyAgentTypeCorbaDef::Key region,
			in DutyAgentTypeCorbaDef::Key subsystem, in DutyAgentTypeCorbaDef::Key profile,
			out DutyAgentTypeCorbaDef::Key actionGroup )
			raises( TA_Base_Core::BadParameterException, TA_Base_Core::DatabaseErrorException,
					TA_Base_Core::OperationModeException, DutyAgentTypeCorbaDef::UnhandledException );

		// Called by Control Stations
		boolean queryHasExclusiveDuty( in TA_Base_Bus::IAuthenticationAgentCorbaDef::SessionInfoCorbaDef session,
			out DutyAgentTypeCorbaDef::SubsystemTreeSequence subsystems )
			raises( TA_Base_Core::BadParameterException, TA_Base_Core::DatabaseErrorException,
					TA_Base_Core::OperationModeException, DutyAgentTypeCorbaDef::UnhandledException );
	}; 
};

#endif //IDUTYAGENTQUERYCORBADEF_H_INCLUDED
