#if !defined(ConfigUpdateMessage_241159C4_E5D8_4ce0_8DFE_D825F80D0D45__INCLUDED_)
#define ConfigUpdateMessage_241159C4_E5D8_4ce0_8DFE_D825F80D0D45__INCLUDED_

/**
  * The source code in this file is the property of 
  * Ripple Systems and is not for redistribution
  * in any form.
  *
  * Source:   $File: //depot/TA_Common_V1_TIP/transactive/core/message/IDL/src/ConfigUpdateMessageCorbaDef.idl $
  * @author:  Cameron Rochester
  * @version: $Revision: #1 $
  *
  * Last modification: $DateTime: 2015/01/19 17:43:23 $
  * Last modified by:  $Author: CM $
  * 
  * Config Update Messages are used by the
  * Transactive Online Update subsystem.
  */

#include "core/message/IDL/src/GenericMessageCorbaDef.idl"

module TA_Base_Core
{
		struct ConfigUpdateMessageCorbaDef
		{
			/**
			 * Time the Message was first generated
			 */
			DateTime createTime;

			/**
			 * The MessageTypeKey as defined in the MESSAGETYPE table
			 */			
			string messageTypeKey;

			/**
			 * An entity associated with this Event
			 */
			unsigned long assocEntityKey;

			/**
			 * The modification type
			 */
			EModificationType modificationType;

			/**
			 * The list of parameter names that have changes
			 */
			StringSequence changes;

		}; // interface ConfigUpdateMessageCorbaDef


}; // module TA_Base_Core

#endif // !defined(ConfigUpdateMessage_241159C4_E5D8_4ce0_8DFE_D825F80D0D45__INCLUDED_)
