#if !defined(StateUpdateMessage_F78F9543_22E9_41e2_B9EB_ACD1B76B3185__INCLUDED_)
#define StateUpdateMessage_F78F9543_22E9_41e2_B9EB_ACD1B76B3185__INCLUDED_

/**
  * The source code in this file is the property of 
  * Ripple Systems and is not for redistribution
  * in any form.
  *
  * Source:   $File: //depot/TA_Common_V1_TIP/transactive/core/message/IDL/src/StateUpdateMessageCorbaDef.idl $
  * @author:  Cameron rochester
  * @version: $Revision: #1 $
  *
  * Last modification: $DateTime: 2015/01/19 17:43:23 $
  * Last modified by:  $Author: CM $
  * 
  * State Update Messages are used by Transactive
  * Agents to update their Monitor agents and for
  * Monitor agents to request an update from their
  * control agent.
  */

#include "core/message/IDL/src/GenericMessageCorbaDef.idl"

module TA_Base_Core
{
		struct StateUpdateMessageCorbaDef
		{
			
			/**
			 * Time the Message was first generated
			 */
			DateTime createTime;

			/**
			 * The MessageTypeKey as defined in the MESSAGETYPE table
			 */			
			string messageTypeKey;

			/**
			 * An entity associated with this Event
			 */
			unsigned long assocEntityKey;

			/**
			 * Any state data
			 */
			any stateUpdateInfo;

		}; // interface StateUpdateMessageCorbaDef


}; // module TA_Base_Core

#endif // !defined(StateUpdateMessage_F78F9543_22E9_41e2_B9EB_ACD1B76B3185__INCLUDED_)
