//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ControlStation.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDP_OLE_INIT_FAILED             100
#define IDD_ARIALBOLD_LOGIN_DIALOG      102
#define IDR_MAINFRAME                   128
#define IDR_RippleControlStation        165
#define IDR_SCHEMATICDISPLAY            166
#define IDR_CONTROLSTATION2             167
#define IDD_LAUNCH_BAR                  169
#define IDD_DUMMY_DIALOG                191
#define IDD_CHANGE_PASSWORD_DIALOG      197
#define IDD_TASK_MANAGER                199
#define IDD_ARIALBOLD_LOGOUT_DIALOG     200
#define IDD_EDIT_SHORTCUT_DIALOG        201
#define IDD_DUTY_REQUEST_DIALOG         202
#define IDD_DUTY_POPUP_DIALOG           203
#define IDC_NAME                        1000
#define IDC_FAVOURITES_COMBO            1000
#define IDC_VERSION                     1001
#define IDC_EXCLUSIVE_DUTY_TEXT         1001
#define IDC_DEVICE_COMBO                1002
#define IDC_DISPLAY_COMBO               1003
#define IDC_PASSWORD_EDIT               1004
#define IDC_NAME_COMBO                  1005
#define IDC_SHORTCUT_LIST               1006
#define IDC_ADD_SHORTCUT                1007
#define IDC_REMOVE_SHORTCUT             1008
#define IDC_MOVE_UP                     1009
#define IDC_MOVE_DOWN                   1010
#define IDC_SET_SHORTCUT                1011
#define IDB_DETAIL                      1012
#define IDB_CLOSE                       1013
#define IDC_LINE1                       1014
#define IDC_LINE2                       1015
#define IDC_LINE3                       1016
#define IDC_COMBO_PROCESS               1024
#define IDC_BUTTON_TERMINATE            1025
#define IDC_BUTTON_ADD_PARAM            1026
#define IDC_LIST_PARAMETERS             1027
#define IDC_PROCESS_FRAME               1028
#define IDC_EDIT_ADD_PARAM              1029
#define IDC_HELP_BUTTON                 1033
#define IDC_LOGOUT_BUTTON               1034
#define IDC_OVERRIDE_BUTTON             1035
#define IDC_DISPLAY_BUTTON1             1036
#define IDC_DISPLAY_BUTTON2             1037
#define IDC_LIST_APPLICATIONS           1038
#define IDC_DISPLAY_BUTTON3             1039
#define IDC_VIEW_CAMERA_BUTTON          1042
#define IDC_VIEW_SHORTCUT_BUTTON        1043
#define IDC_EDIT_SHORTCUT_BUTTON        1044
#define IDC_USER_DETAILS                1051
#define IDC_DISPLAY_SCHEMATIC_BUTTON    1052
#define IDC_STATIC_PROFILE              1053
#define IDC_DISPLAY_BUTTON4             1053
#define IDC_DISPLAY_BUTTON5             1054
#define IDC_STATIC_LOCATION             1054
#define IDC_STATIC_PASSWORD             1055
#define IDC_PROFILE_BUTTON              1055
#define IDC_STATIC_GROUP                1056
#define IDC_OPERATOR_BUTTON             1056
#define IDC_PASSWORD_BUTTON             1057
#define IDC_DATE_TIME_DETAILS           1058
#define IDC_NAME_COMBO_AB               1060
#define IDC_PROFILE_COMBO_AB            1061
#define IDC_LOCATION_COMBO_AB           1062
#define IDC_PASSWORD_EDIT_AB            1063
#define IDC_LOGIN_BUTTON_AB             1064
#define IDC_CANCEL_AB                   1065
#define IDC_EXIT                        1065
#define IDC_RESTART_BUTTON_AB           1066
#define IDC_HELP_BUTTON_AB              1067
#define IDC_STATUS_AB                   1068
#define IDC_ANIMATE_AB                  1069
#define IDC_STATUS_AB2                  1070
#define IDC_NEW_PASSWORD_EDIT           1071
#define IDC_CONFIRM_PASSWORD_EDIT       1075
#define IDC_EXIT_BUTTON                 1076
#define IDC_RESTART_BUTTON              1077
#define IDC_DUTY_TIMEOUT                1078
#define IDC_DUTY_TEXT                   1079
#define IDC_DUTY_TEXT2                  1080
#define IDC_DUTY_TEXT3                  1081
#define IDC_DUTY_TEXT4                  1082
#define IDC_DENY                        1083
#define ID_RESSAVER                     1084
#define IDR_REGISTRY1                   10085
#define IDD_EXCLUSIVE_DUTY_DIALOG       10086
#define IDD_DIALOG1                     10087
#define IDD_DIALOG_DUTY_CHANGE          10088
#define IDS_ABOUTBOX                    57347
#define IDS_REQUESTED_APPLICATION       57348
#define IDS_EXIT                        57349
#define IDS_RESTART                     57350
#define IDS_CHANGE_PROFILE              57351
#define IDS_CHANGE_OPERATOR             57352
#define IDS_OPERATOR_OVERRIDE           57353
#define IDS_CHANGE_PASSWORD             57354
#define IDS_LOGOUT                      57355
#define IDS_LOGIN                       57356
#define IDS_ONLINE                      57357
#define IDS_OFFLINE                     57358
#define IDS_OPERATOR                    57359
#define IDS_PROFILE                     57360
#define IDS_LOCATION                    57361
#define IDS_DISPLAY                     57362
#define IDS_APPNAME                     57363
#define IDS_BANNER                      57364
#define IDS_REMOVE_OPERATOR_OVERRIDE    57365
#define IDS_TASK_MANAGER                57366
#define IDS_SHORTCUT_NAME               57367
#define IDS_SUBSYSTEM                   57368
#define IDS_AUTHENTICATION_AGENT        57369
#define IDS_SUCC                        57370
#define IDS_FAIL                        57371
#define IDS_SCRFILENAME                 57372
#define IDS_PASSWORD                    57373
#define IDS_REQUEST_FORMAT_WITH_LOCATION 57374
#define IDS_LOCATION_AND_SUBSYSTEM_FORMAT 57375
#define IDS_SUBSYSTEM_FORMAT            57376
#define IDS_PRE_TIMEOUT_FORMAT          57377
#define IDS_POST_TIMEOUT_FORMAT         57378
#define IDS_REQUEST_FORMAT_WITHOUT_LOCATION 57379
#define IDS_ERROR_MESSAGE               57380

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        10088
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1017
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
