//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by AlarmsGui.rc
//
#define IDD_ALARMSGUI_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDD_FILTERS                     131
#define IDI_ACKNOWLEDGE                 132
#define IDB_BITMAP1                     133
#define IDI_DELETE_HOT                  134
#define IDB_BITMAP2                     135
#define IDI_ACKNOWLEDGE_HOT             136
#define IDI_DELETE                      137
#define IDR_MONITOR_MENU                138
#define IDI_VIEWCAM_HOT                 139
#define IDI_VIEWCAM                     140
#define IDI_REFRESH_HOT                 141
#define IDI_PLAN_HOT                    142
#define IDI_PRINT                       143
#define IDI_PRINT_HOT                   144
#define IDI_REFRESH                     145
#define IDI_PLAN                        146
#define IDI_SILENCE_HOT                 147
#define IDI_DETAIL_HOT                  150
#define IDI_SILENCE                     151
#define IDI_DETAIL                      152
#define IDI_APPLY_FILTERS_HOT           153
#define IDI_APPLY_FILTERS               154
#define IDI_SHOW_FILTERS_HOT            155
#define IDD_MULTIPLE_LOAD               156
#define IDI_SHOW_FILTERS                157
#define IDI_SM_BELL                     158
#define IDD_RULES                       159
#define IDD_PLAN_SELECTION              160
#define IDB_AM_COMMENTS                 163
#define IDI_COMMENT_HOT                 165
#define IDR_ACCELERATOR1                168
#define IDR_AM_MAIN_MENU                173
#define IDB_COMMENTSGREY                176
#define IDI_SORT                        179
#define IDI_SORT_HOT                    180
#define IDI_MANUAL_CLOSE_HOT            183
#define IDI_MANUAL_CLOSE                185
#define IDI_TBAR                        300
#define IDI_TBAR_HOT                    301
#define IDI_SUPPRESS_HOT                302
#define IDI_SUPPRESS                    303
#define IDI_SHOW_RULES_HOT              304
#define IDI_SHOW_RULES                  305
#define IDI_SAVE_HOT                    306
#define IDI_SAVE                        307
#define IDI_VIEWS_HOT                   308
#define IDI_VIEWS                       309
#define IDC_ALARMS_TOOLBAR              407
#define IDC_ALARMS_TBAR                 408
#define IDC_ALARM_LIST                  409
#define IDC_LOAD_LIST                   410
#define IDC_FILTER_LIST                 411
#define IDC_EDIT_FROM                   412
#define IDC_EDIT_TO                     413
#define IDC_NOT_ACKED                   414
#define IDC_STATUSBAR                   415
#define IDC_ACK_CHECK                   420
#define IDC_AREA_CHECK                  421
#define IDC_ENTITY_CHECK                422
#define IDC_SYSTEM_CHECK                423
#define IDC_ACK_COMBO                   424
#define IDC_AREA_COMBO                  425
#define IDC_ENTITY_COMBO                426
#define IDC_SYSTEM_COMBO                427
#define IDC_APPLY                       429
#define IDC_PROGRESS                    430
#define IDC_RULES_LIST                  431
#define IDC_REMOVE_BUTTON               432
#define IDC_CLOSE                       433
#define IDC_REFRESH                     434
#define IDC_PAGER_CTRL                  435
#define IDC_COMBO1                      436
#define IDC_MENU_LINE                   437
#define IDC_SAVE                        438
#define IDC_STATIC_TOTALARMS            439
#define IDC_STATIC_NOTACK               440
#define IDC_TOTAL_ALARMS                441
#define IDC_STATIC_CURRENT_FILTER       442
#define IDC_NAMED_FILTER                443
#define IDC_BUTTON1                     444
#define IDC_PRINT_LIST                  445
#define IDC_EXPORT_LIST                 446
#define ID_TOOLS_LAUNCHCAMERA           560
#define ID_LAUNCH_CAM_CTRL              561
#define IDK_UNSELECT_KEY                563
#define ID_FILE_EXPORT                  564
#define ID_ALARM_DELETE                 566
#define ID_ALARM_INHIBIT                567
#define ID_ALARM_ADDCOMMENT             568
#define ID_TOOLS_RUNPLAN                569
#define ID_TOOLS_SILENCE                571
#define ID_VIEW_APPLYFILTERS            572
#define ID_VIEW_SHOWFILTERS             573
#define ID_VIEW_SHOWINHIBITIONS         574
#define ID_VIEW_REFRESH                 575
#define ID_ALARM_ALL_ACKNOWLEDGE        576
#define ID_TOOLS_LAUNCHVIEW             577
#define ID_VIEW_COLUMN_ALARMTYPE        578
#define ID_VIEW_COLUMN_SYSTEM           579
#define ID_VIEW_COLUMN_TIME_LOGGED      580
#define ID_VIEW_COLUMN_ACKNOWLEDGE      581
#define ID_VIEW_COLUMN_STATE            582
#define ID_VIEW_COLUMN_REGION           583
#define ID_LOAD_DISPLAY                 584
#define ID_FILE_CLOSE_APPLICATION       585
#define ID_FILE_EXIT                    586
#define ID_RUN_PLAN                     587
#define ID_RELATED_INSPECTOR            588
#define ID_AM_ALARM_ACKNOWLEDGE         589
#define ID_ALARM                        590
#define ID_RELATED_TREND                591
#define ID_AM_ALARM_SCHEMATIC           592
#define ID_JOB_REQUEST                  600
#define ID_AM_ALARM_MANUAL_CLOSE        601
#define ID_AM_ALARM_INSPECTOR           602
#define ID_AM_ALARM_PLAN                603
#define ID_VIEW_COLUMN_COMMENTS         604
#define ID_AM_ALARM_TREND               605
#define ID_AM_ALARM_JOB_REQUEST         606
#define ID_AM_ALARM_EVENT_LOG           607
#define ID_AM_ALARM_EVENTS              608
#define ID_AM_CANCEL_ALARM_PLAN         609
#define ID_VIEW_COLUMN_SOURCE_TIME      610
#define ID_VIEW_COLUMN_ACKBY            611
#define ID_VIEW_COLUMN_ASSET            612
#define ID_VIEW_COLUMN_LOCATION         613
#define ID_VIEW_COLUMN_DESCRIPTION      614
#define ID_VIEW_COLUMN_TRANSACTIVE_TIMESTAMP 615
#define ID_VIEW_COLUMN_SEVERITY         616
#define ID_VIEW_COLUMN_VALUE            617
#define ID_VIEW_COLUMN_AVL              618
#define ID_VIEW_COLUMN_DSS              619
#define ID_VIEW_COLUMN_MMS              620
#define ID_VIEW_COLUMN_ACKTIME          621
#define ID_AM_ALARM_AVALANCHE_EVENTS    622
#define ID_AM_ALARM_PLAN_INSTANCE		623
#define IDC_REFRESH_BUTTON              901
#define ID_CLEAR_FILTERS_BUTTON         902
#define IDC_CLEAR_FILTERS_BUTTON        903
#define ID_CLEAR_FILTERS_BUTTON2        904
#define ID_SET_AS_DEFAULT_BUTTON        905
#define IDI_COMMENTS                    906
#define IDI_COMMENT                     907
#define IDI_UNACKBOX                    910
#define IDB_COMMENTS                    911
#define IDB_DOWN                        912
#define IDB_UP                          913
#define IDD_ALARM_FILTER                914
#define ID_AM_ALARM_VIEW_COMMENT        915
#define IDD_MULTIPLE_SEL_DLG            916
#define IDI_EVENT_VIEWER_COLD           917
#define IDI_EVENT_VIEWER_HOT            918
#define IDC_ALARMLISTBOX_OK             1001
#define IDC_ALARMLISTBOX_CANCEL         1003
#define IDC_ALARMPLANLISTBOX            1007
#define IDC_SILENCE                     1025
#define ID_ALARM_ACKNOWLEDGE            1026
#define ID_ALARM_SCHEMATIC              1027
#define ID_ALARM_INSPECTOR              1028
#define ID_ALARM_PLAN                   1029
#define ID_ALARM_TREND                  1030
#define ID_ALARM_JOB_REQUEST            1031
#define ID_ALARM_EVENT_LOG              1032
#define IDC_SEVERITY_STATIC             2003
#define IDC_SUBSYSTEM_STATIC            2004
#define IDC_LOCATION_STATIC             2005
#define IDC_ALARM_STATUS_STATIC         2006
#define IDC_OPERATOR_STATIC             2007
#define IDC_ALARMT_TYPE_STATIC          2008
#define IDC_ASSET_STATIC                2009
#define IDC_DESCRIPTION_STATIC          2010
#define IDC_APPLY_BUTTON                2011
#define IDC_COMBO_SUBSYSTEM             2012
#define IDC_COMBO_LOCATION              2013
#define IDC_COMBO_OPERATOR              2014
#define IDC_COMBO_SEVERITY              2015
#define IDC_COMBO_ASSET                 2016
#define IDC_EDIT_ASSET                  2017
#define IDC_COMBO_ACK                   2018
#define IDC_EDIT_DESCRIPTION            2019
#define IDC_COMBO_STATE                 2020
#define IDC_COMBO_ALARM_TYPE            2021
#define IDC_DATETIMEPICKER_FROMDATE     2022
#define IDC_STATIC_FROM                 2023
#define IDC_DATETIMEPICKER_FROMTIME     2024
#define IDC_ALARM_STATUS_STATIC2        2025
#define IDC_DATETIMEPICKER_TODATE       2026
#define IDC_DATETIMEPICKER_TOTIME       2027
#define IDC_STATIC_TO                   2028
#define IDC_MULTI_SEL_LIST              2029
#define IDC_SUBSYSTEM_BUTTON            2030
#define ID_MULTIOK                      2031
#define IDC_LOCATION_BUTTON             2032
#define IDC_SUBSYSTEM_EDIT              2033
#define IDC_LOCATION_EDIT               2034
#define ID_ALARM_MANUAL_CLOSE           2035
#define ID_ALARM_EVENTS                 2036
#define IDC_ALARM_TYPE_BUTTON           2037
#define IDC_ALARM_TYPE_EDIT             2038
#define IDC_OPERATOR_EDIT               2039
#define ID_MULTI_UNSELECT               2040
#define IDC_OPERATOR_BUTTON             2041
#define IDI_BLANK                       3008
#define IDI_RULE_UNREMOVABLE            3010
#define IDI_UNREMOVABLE_RULE            3010
#define IDI_RULE_REMOVABLE              3011
#define IDB_BITMAP3                     3012
#define ID_AM_INHIBIT_BY_TYPE           3013
#define ID_AM_INHIBIT_BY_DESCRIPTION    3014
#define IDC_FROM_TIME                   5000
#define IDC_TO_TIME                     5001
#define IDC_STATE_OPEN                  5002
#define IDC_STATE_CLOSED                5003
#define IDC_STATE_ALL                   5004
#define IDC_STATE                       5005
#define IDC_ACK_GROUP                   5006
#define IDC_ACK_ACKED                   5007
#define IDC_ACK_UNACKED                 5008
#define IDC_ACK_ALL                     5009
#define IDC_RADIO_FILTER_LOCATION       5014
#define IDC_DELETE                      5015
#define IDC_NAMED_FILTER_BOX            5016
#define IDC_LIST_PLACEHOLDER            5017
#define IDC_SEVERITY_LIST               5018
#define IDC_LIST1                       5019
#define IDC_RADIO_SHOW_ALL              5020
#define ID_CANCEL                       5021
#define IDC_CANCEL                      5021
#define ID_OK                           5022
#define IDC_OK                          5022
#define IDC_COMBO_FROM                  5023
#define IDC_COMBO_TO                    5024
#define IDC_SPIN_FROM                   5025
#define IDC_SPIN_TO                     5026
#define IDC_COMBO_LOCATIONS             5027

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        3013
#define _APS_NEXT_COMMAND_VALUE         4006
#define _APS_NEXT_CONTROL_VALUE         5030
#define _APS_NEXT_SYMED_VALUE           6000
#endif
#endif
