/**
 * The source code in this file is the property of 
 * Ripple Systems and is not for redistribution
 * in any form.
 *
 * Source:   $File: //depot/TA_Common_V1_TIP/transactive/bus/alarm/alarm_list_control/src/actions/ActionResources.h $
 * @author:  Karen Graham
 * @version: $Revision: #1 $
 *
 * Last modification: $DateTime: 2015/01/19 17:43:23 $
 * Last modified by:  $Author: CM $
 * 
 * This file should be updated whenever a new alarm action is added so it is easy to tell which resource
 * to use and which ones are free
 */

#define SEPARATOR                3999
#define VIEW_COMMENT             4000     // &View Comment...
#define ACKNOWLEDGE_ALARM        4001     // &Acknowledge Selection
#define EDIT_COMMENT             4002     // Edit Co&mment...
#define RELATED_SCHEMATIC        4003     // Related &Schematic
#define CLOSE_AND_ACK_ALARM      4004     // &Close and Ack Selection
#define RELATED_INSPECTOR        4005     // Related &Inspector...
#define RELATED_DSS              4006     // Related &DSS...
#define POSTPONE_DSS             4007     // &Postpone DSS
#define RELATED_TREND            4008     // Related &Trend...
#define RELATED_EVENTS           4009     // Related &Events...
#define JOB_REQUEST              4010     // &Job Request...
#define INCIDENT_LOG_SHEET       4011     // Create Incident &Report...
#define ACKNOWLEDGE_ALL          4012     // Acknowledge All
#define RELATED_AVALANCHE_EVENTS 4013	  // Related A&valanche Events...
#define INHIBIT_ALARM            4014     // I&nhibit...
#define INHIBIT_ALARM_BY_TYPE	 4016     // By T&ype...
#define INHIBIT_ALARM_BY_DESCRIPTION 4017 // By Descripti&on...
#define EVENTS_VIEWER            4015     // Events Vie&wer
#define RELATED_PLAN_INSTANCE    4018     //Related &Plan Instance...
//#define ??                       4017
// ...
//#define ??                       4999