# The source code in this file is the property of
# Ripple Systems and is not for redistribution
# in any form.
#
# Source:   $File: //depot/TA_Common_V1_TIP/transactive/bus/generic_server_simulator/examples/echo_server/Makefile $
# @author:  Ripple
# @version: $Revision: #1 $
#
# Last modification: $DateTime: 2015/01/19 17:43:23 $
# Last modified by:  $Author: CM $
#
# This file builds the EchoServerExample library
PROJ_ROOT_DIR = ../../../..
PROJ_NAME	= EchoServerExample
PROJ_SOURCE	= EchoCommsObserver.cpp \
		EchoModuleCreator.cpp \
		EchoSimulationModule.cpp

PROJ_TYPE	= lib
PROJ_OBJDIR	= ./obj
PROJ_INCDIR	= ./src \
		$(PROJ_ROOT_DIR)

##############################################################
# The main include file that has all the wiz bang stuff for neato compiling
##############################################################
include $(PROJ_ROOT_DIR)/tools/build/CommonMakefile.mak


install:
	#Do Nothing

