#if !defined(DATALOG_MESSAGE_IDL)
#define DATALOG_MESSAGE_IDL

/**
  * The source code in this file is the property of 
  * Ripple Systems and is not for redistribution
  * in any form.
  *
  * Source:   $File: //depot/4669_Review_Branch/TA_BASE/transactive/core/datalog/IDL/src/DatalogMessageCorbaDef.idl $
  * @author:  luohuirong
  * @version: $Revision: #1 $
  *
  * Last modification: $DateTime: 2010/12/13 11:17:43 $
  * Last modified by:  $Author: luohuirong$
  * 
  * Datalog Messages are used to sync log between control agent and monitor agent
  * events in the transactive system
  */
 
#include "core/message/IDL/src/GenericMessageCorbaDef.idl"

module TA_Base_Core
{ 
	struct DataLogSyncCorbaDef
	{
	    
		/**
		* the pkey of DataLog category
		*/
		unsigned long pkey;

		/**
          * The type of DataLog category
        */
        string categoryType;
		
		/**
          * The late log time
        */		
		TA_Base_Core::DateTime latestLogTime;

	};     

	typedef sequence<DataLogSyncCorbaDef> DataLogSyncSequence;

}; // module TA_Base_Core

#endif // !defined(DATALOG_MESSAGE_IDL)
