// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __DatalogAgentCorbaDef_hh__
#define __DatalogAgentCorbaDef_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_DatalogAgentCorbaDef
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_DatalogAgentCorbaDef
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_DatalogAgentCorbaDef
#endif



#ifndef __GenericMessageCorbaDef_hh_EXTERNAL_GUARD__
#define __GenericMessageCorbaDef_hh_EXTERNAL_GUARD__
#include <GenericMessageCorbaDef.h>
#endif
#ifndef __DataLogMessageCorbaDef_hh_EXTERNAL_GUARD__
#define __DataLogMessageCorbaDef_hh_EXTERNAL_GUARD__
#include <DataLogMessageCorbaDef.h>
#endif
#ifndef __CommonExceptionsCorbaDef_hh_EXTERNAL_GUARD__
#define __CommonExceptionsCorbaDef_hh_EXTERNAL_GUARD__
#include <CommonExceptionsCorbaDef.h>
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE TA_Base_Core

_CORBA_MODULE_BEG

  _CORBA_MODULE_VAR _core_attr const char * DATALOG_AGENT_NAME;

#ifndef __TA__Base__Core_mDataLogAgentCorbaDef__
#define __TA__Base__Core_mDataLogAgentCorbaDef__

  class DataLogAgentCorbaDef;
  class _objref_DataLogAgentCorbaDef;
  class _impl_DataLogAgentCorbaDef;
  
  typedef _objref_DataLogAgentCorbaDef* DataLogAgentCorbaDef_ptr;
  typedef DataLogAgentCorbaDef_ptr DataLogAgentCorbaDefRef;

  class DataLogAgentCorbaDef_Helper {
  public:
    typedef DataLogAgentCorbaDef_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_DataLogAgentCorbaDef, DataLogAgentCorbaDef_Helper> DataLogAgentCorbaDef_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_DataLogAgentCorbaDef,DataLogAgentCorbaDef_Helper > DataLogAgentCorbaDef_out;

#endif

  // interface DataLogAgentCorbaDef
  class DataLogAgentCorbaDef {
  public:
    // Declarations for this interface type.
    typedef DataLogAgentCorbaDef_ptr _ptr_type;
    typedef DataLogAgentCorbaDef_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    class DataLogException : public ::CORBA::UserException {
    public:
      
      ::CORBA::String_member reason;

    

      inline DataLogException() {
        pd_insertToAnyFn    = insertToAnyFn;
        pd_insertToAnyFnNCP = insertToAnyFnNCP;
      }
      DataLogException(const DataLogException&);
      DataLogException(const char* i_reason);
      DataLogException& operator=(const DataLogException&);
      virtual ~DataLogException();
      virtual void _raise() const;
      static DataLogException* _downcast(::CORBA::Exception*);
      static const DataLogException* _downcast(const ::CORBA::Exception*);
      static inline DataLogException* _narrow(::CORBA::Exception* _e) {
        return _downcast(_e);
      }
      
      void operator>>=(cdrStream&) const ;
      void operator<<=(cdrStream&) ;

      static _core_attr insertExceptionToAny    insertToAnyFn;
      static _core_attr insertExceptionToAnyNCP insertToAnyFnNCP;

      virtual ::CORBA::Exception* _NP_duplicate() const;

      static _core_attr const char* _PD_repoId;
      static _core_attr const char* _PD_typeId;

    private:
      virtual const char* _NP_typeId() const;
      virtual const char* _NP_repoId(int*) const;
      virtual void _NP_marshal(cdrStream&) const;
    };

    static _dyn_attr const ::CORBA::TypeCode_ptr _tc_DataLogException;

  
  };

  class _objref_DataLogAgentCorbaDef :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    DataLogSyncSequence* getAllDataLogSync();

    inline _objref_DataLogAgentCorbaDef()  { _PR_setobj(0); }  // nil
    _objref_DataLogAgentCorbaDef(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_DataLogAgentCorbaDef();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_DataLogAgentCorbaDef(const _objref_DataLogAgentCorbaDef&);
    _objref_DataLogAgentCorbaDef& operator = (const _objref_DataLogAgentCorbaDef&);
    // not implemented

    friend class DataLogAgentCorbaDef;
  };

  class _pof_DataLogAgentCorbaDef : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_DataLogAgentCorbaDef() : _OMNI_NS(proxyObjectFactory)(DataLogAgentCorbaDef::_PD_repoId) {}
    virtual ~_pof_DataLogAgentCorbaDef();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_DataLogAgentCorbaDef :
    public virtual omniServant
  {
  public:
    virtual ~_impl_DataLogAgentCorbaDef();

    virtual DataLogSyncSequence* getAllDataLogSync() = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_DataLogAgentCorbaDef;

_CORBA_MODULE_END



_CORBA_MODULE POA_TA_Base_Core
_CORBA_MODULE_BEG

  class DataLogAgentCorbaDef :
    public virtual TA_Base_Core::_impl_DataLogAgentCorbaDef,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~DataLogAgentCorbaDef();

    inline ::TA_Base_Core::DataLogAgentCorbaDef_ptr _this() {
      return (::TA_Base_Core::DataLogAgentCorbaDef_ptr) _do_this(::TA_Base_Core::DataLogAgentCorbaDef::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_TA_Base_Core
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, const TA_Base_Core::DataLogAgentCorbaDef::DataLogException& _s);
void operator<<=(::CORBA::Any& _a, const TA_Base_Core::DataLogAgentCorbaDef::DataLogException* _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const TA_Base_Core::DataLogAgentCorbaDef::DataLogException*& _sp);

void operator<<=(::CORBA::Any& _a, TA_Base_Core::DataLogAgentCorbaDef_ptr _s);
void operator<<=(::CORBA::Any& _a, TA_Base_Core::DataLogAgentCorbaDef_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, TA_Base_Core::DataLogAgentCorbaDef_ptr& _s);



inline void
TA_Base_Core::DataLogAgentCorbaDef::_marshalObjRef(::TA_Base_Core::DataLogAgentCorbaDef_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_DatalogAgentCorbaDef
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_DatalogAgentCorbaDef
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_DatalogAgentCorbaDef
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_DatalogAgentCorbaDef
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_DatalogAgentCorbaDef
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_DatalogAgentCorbaDef
#endif

#endif  // __DatalogAgentCorbaDef_hh__

