// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __ITrainPaMethod_hh__
#define __ITrainPaMethod_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_ITrainPaMethod
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_ITrainPaMethod
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_ITrainPaMethod
#endif



#ifndef __CommonExceptionsCorbaDef_hh_EXTERNAL_GUARD__
#define __CommonExceptionsCorbaDef_hh_EXTERNAL_GUARD__
#include <core/exceptions/IDL/src/CommonExceptionsCorbaDef.h>
#endif
#ifndef __IPAAgentCorbaDef_hh_EXTERNAL_GUARD__
#define __IPAAgentCorbaDef_hh_EXTERNAL_GUARD__
#include <bus/pa/pa_agent/IDL/src/IPAAgentCorbaDef.h>
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE TA_Base_Bus

_CORBA_MODULE_BEG

#ifndef __TA__Base__Bus_mITrainPaMethod__
#define __TA__Base__Bus_mITrainPaMethod__

  class ITrainPaMethod;
  class _objref_ITrainPaMethod;
  class _impl_ITrainPaMethod;
  
  typedef _objref_ITrainPaMethod* ITrainPaMethod_ptr;
  typedef ITrainPaMethod_ptr ITrainPaMethodRef;

  class ITrainPaMethod_Helper {
  public:
    typedef ITrainPaMethod_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_ITrainPaMethod, ITrainPaMethod_Helper> ITrainPaMethod_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_ITrainPaMethod,ITrainPaMethod_Helper > ITrainPaMethod_out;

#endif

  // interface ITrainPaMethod
  class ITrainPaMethod {
  public:
    // Declarations for this interface type.
    typedef ITrainPaMethod_ptr _ptr_type;
    typedef ITrainPaMethod_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_ITrainPaMethod :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    char* broadcastTrainDva(const ::TA_Base_Bus::IPAAgentCorbaDef::TrainCoverage& trains, ::CORBA::ULong messageKey, ::CORBA::ULong libraryVersion, const ::TA_Base_Bus::IPAAgentCorbaDef::TrainCyclicParams& announcementPeriod, ::CORBA::Boolean hasOverrideOption, const char* sessionId, ::CORBA::Boolean bEmergency);
    char* broadcastTrainLive(const ::TA_Base_Bus::IPAAgentCorbaDef::TrainCoverage& trains, ::CORBA::Boolean hasOverrideOption, const char* staticGroup, const char* sessionId);
    void beginTrainLiveAnnouncement(const char* broadcastId);
    void continueTrainLiveAnnouncement(const char* broadcastId);
    void endTrainLiveAnnouncement(const char* broadcastId);
    void retryTrainBroadcast(const char* broadcastId, const ::TA_Base_Bus::IPAAgentCorbaDef::TrainCoverage& trains, ::CORBA::Boolean hasOverrideOption, const char* sessionId);
    void terminateBroadcast(const char* broadcastId, const char* sessionId);
    void removeBroadcast(const char* broadcastId, const char* sessionId);
    IPAAgentCorbaDef::BroadcastIdTypeSeq* getBroadcastIdTypes();
    void changeBroadcastId(const char* fromBroadcastId, const char* toBroadcastId, const char* sessionId);
    IPAAgentCorbaDef::BroadcastConfig* getBroadcastConfig(const char* broadcastId);
    IPAAgentCorbaDef::ProgressReport* getProgressReport(const char* broadcastId);
    IPAAgentCorbaDef::TrainDvaMessageRecords* getTrainDvaMessageRecords();
    void broadcastEventTriggeredTrainDva(::CORBA::ULong messageKey, ::CORBA::Short libraryVersion, const ::TA_Base_Bus::IPAAgentCorbaDef::TrainCyclicParams& announcementPeriod, const char* sessionId, const ::TA_Base_Bus::IPAAgentCorbaDef::TrainCoverage& trains);
    void broadcastEventTriggeredTrainDvaForStation(::CORBA::ULong messageKey, ::CORBA::Short libraryVersion, const ::TA_Base_Bus::IPAAgentCorbaDef::TrainCyclicParams& announcementPeriod, const char* sessionId);
    void broadcastEventTriggeredTrainDvaForInbound(::CORBA::ULong messageKey, ::CORBA::Short libraryVersion, const ::TA_Base_Bus::IPAAgentCorbaDef::TrainCyclicParams& announcementPeriod, const char* sessionId);
    void broadcastEventTriggeredTrainDvaForOutbound(::CORBA::ULong messageKey, ::CORBA::Short libraryVersion, const ::TA_Base_Bus::IPAAgentCorbaDef::TrainCyclicParams& announcementPeriod, const char* sessionId);

    inline _objref_ITrainPaMethod()  { _PR_setobj(0); }  // nil
    _objref_ITrainPaMethod(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_ITrainPaMethod();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_ITrainPaMethod(const _objref_ITrainPaMethod&);
    _objref_ITrainPaMethod& operator = (const _objref_ITrainPaMethod&);
    // not implemented

    friend class ITrainPaMethod;
  };

  class _pof_ITrainPaMethod : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_ITrainPaMethod() : _OMNI_NS(proxyObjectFactory)(ITrainPaMethod::_PD_repoId) {}
    virtual ~_pof_ITrainPaMethod();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_ITrainPaMethod :
    public virtual omniServant
  {
  public:
    virtual ~_impl_ITrainPaMethod();

    virtual char* broadcastTrainDva(const ::TA_Base_Bus::IPAAgentCorbaDef::TrainCoverage& trains, ::CORBA::ULong messageKey, ::CORBA::ULong libraryVersion, const ::TA_Base_Bus::IPAAgentCorbaDef::TrainCyclicParams& announcementPeriod, ::CORBA::Boolean hasOverrideOption, const char* sessionId, ::CORBA::Boolean bEmergency) = 0;
    virtual char* broadcastTrainLive(const ::TA_Base_Bus::IPAAgentCorbaDef::TrainCoverage& trains, ::CORBA::Boolean hasOverrideOption, const char* staticGroup, const char* sessionId) = 0;
    virtual void beginTrainLiveAnnouncement(const char* broadcastId) = 0;
    virtual void continueTrainLiveAnnouncement(const char* broadcastId) = 0;
    virtual void endTrainLiveAnnouncement(const char* broadcastId) = 0;
    virtual void retryTrainBroadcast(const char* broadcastId, const ::TA_Base_Bus::IPAAgentCorbaDef::TrainCoverage& trains, ::CORBA::Boolean hasOverrideOption, const char* sessionId) = 0;
    virtual void terminateBroadcast(const char* broadcastId, const char* sessionId) = 0;
    virtual void removeBroadcast(const char* broadcastId, const char* sessionId) = 0;
    virtual IPAAgentCorbaDef::BroadcastIdTypeSeq* getBroadcastIdTypes() = 0;
    virtual void changeBroadcastId(const char* fromBroadcastId, const char* toBroadcastId, const char* sessionId) = 0;
    virtual IPAAgentCorbaDef::BroadcastConfig* getBroadcastConfig(const char* broadcastId) = 0;
    virtual IPAAgentCorbaDef::ProgressReport* getProgressReport(const char* broadcastId) = 0;
    virtual IPAAgentCorbaDef::TrainDvaMessageRecords* getTrainDvaMessageRecords() = 0;
    virtual void broadcastEventTriggeredTrainDva(::CORBA::ULong messageKey, ::CORBA::Short libraryVersion, const ::TA_Base_Bus::IPAAgentCorbaDef::TrainCyclicParams& announcementPeriod, const char* sessionId, const ::TA_Base_Bus::IPAAgentCorbaDef::TrainCoverage& trains) = 0;
    virtual void broadcastEventTriggeredTrainDvaForStation(::CORBA::ULong messageKey, ::CORBA::Short libraryVersion, const ::TA_Base_Bus::IPAAgentCorbaDef::TrainCyclicParams& announcementPeriod, const char* sessionId) = 0;
    virtual void broadcastEventTriggeredTrainDvaForInbound(::CORBA::ULong messageKey, ::CORBA::Short libraryVersion, const ::TA_Base_Bus::IPAAgentCorbaDef::TrainCyclicParams& announcementPeriod, const char* sessionId) = 0;
    virtual void broadcastEventTriggeredTrainDvaForOutbound(::CORBA::ULong messageKey, ::CORBA::Short libraryVersion, const ::TA_Base_Bus::IPAAgentCorbaDef::TrainCyclicParams& announcementPeriod, const char* sessionId) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_ITrainPaMethod;

_CORBA_MODULE_END



_CORBA_MODULE POA_TA_Base_Bus
_CORBA_MODULE_BEG

  class ITrainPaMethod :
    public virtual TA_Base_Bus::_impl_ITrainPaMethod,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~ITrainPaMethod();

    inline ::TA_Base_Bus::ITrainPaMethod_ptr _this() {
      return (::TA_Base_Bus::ITrainPaMethod_ptr) _do_this(::TA_Base_Bus::ITrainPaMethod::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_TA_Base_Bus
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, TA_Base_Bus::ITrainPaMethod_ptr _s);
void operator<<=(::CORBA::Any& _a, TA_Base_Bus::ITrainPaMethod_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, TA_Base_Bus::ITrainPaMethod_ptr& _s);



inline void
TA_Base_Bus::ITrainPaMethod::_marshalObjRef(::TA_Base_Bus::ITrainPaMethod_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_ITrainPaMethod
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_ITrainPaMethod
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_ITrainPaMethod
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_ITrainPaMethod
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_ITrainPaMethod
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_ITrainPaMethod
#endif

#endif  // __ITrainPaMethod_hh__

