// File: AlarmNotUsed_MessageTypes.h
// Created: 12/04/2006 4:13:29 PM
// This file is automatically generated from 9999D02170001-TransActive_CORBA_Messages_Register.xls
// Reference: 9999-D02-17-0001, Version: 34.06, Status: Draft, Dated: 06 Apr 06
//
// * DO NOT MODIFY! *

#ifndef ALARMNOTUSED_MESSAGETYPES_H
#define ALARMNOTUSED_MESSAGETYPES_H

#include "MessageTypes.h"

namespace TA_Base_Core
{
	namespace AlarmNotUsed
	{
		// Root context
		static MessageContext Context("Alarm", "AlarmNotUsed", AlarmMessage);

		// Message Types for context AlarmNotUsed
	};
};

#endif // ALARMNOTUSED_MESSAGETYPES_H
