// File: AlarmStateUpdate_MessageTypes.h
// Created: 12/04/2006 4:13:30 PM
// This file is automatically generated from 9999D02170001-TransActive_CORBA_Messages_Register.xls
// Reference: 9999-D02-17-0001, Version: 34.06, Status: Draft, Dated: 06 Apr 06
//
// * DO NOT MODIFY! *

#ifndef ALARMSTATEUPDATE_MESSAGETYPES_H
#define ALARMSTATEUPDATE_MESSAGETYPES_H

#include "MessageTypes.h"

namespace TA_Base_Core
{
	namespace AlarmStateUpdate
	{
		// Root context
		static MessageContext Context("StateUpdate", "AlarmStateUpdate", StateUpdateMessage);

		// Message Types for context AlarmStateUpdate
		static const MessageType AlarmAgentBatchCacheUpdate(Context, "10002");
		static const MessageType AlarmAgentBatchQueueUpdate(Context, "10003");
		static const MessageType AlarmAgentBatchRuleQueueUpdate(Context, "10004");
		static const MessageType AlarmAgentBatchRuleUpdate(Context, "10005");
		static const MessageType AlarmAgentStateRequest(Context, "10006");
		static const MessageType AlarmStateUpdate(Context, "10007");
		static const MessageType QueueItemRemoved(Context, "10008");
	};
};

#endif // ALARMSTATEUPDATE_MESSAGETYPES_H
