// File: ApplicationStatusAudit_MessageTypes.h
// Created: 12/04/2006 4:13:30 PM
// This file is automatically generated from 9999D02170001-TransActive_CORBA_Messages_Register.xls
// Reference: 9999-D02-17-0001, Version: 34.06, Status: Draft, Dated: 06 Apr 06
//
// * DO NOT MODIFY! *

#ifndef APPLICATIONSTATUSAUDIT_MESSAGETYPES_H
#define APPLICATIONSTATUSAUDIT_MESSAGETYPES_H

#include "MessageTypes.h"

namespace TA_Base_Core
{
	namespace ApplicationStatusAudit
	{
		// Root context
		static MessageContext Context("Audit", "ApplicationStatusAudit", AuditMessage);

		// Message Types for context ApplicationStatusAudit
		static const MessageType ApplicationExit(Context, "30131");
		static const MessageType ApplicationLaunchFailure(Context, "30132");
		static const MessageType ApplicationStart(Context, "30133");
	};
};

#endif // APPLICATIONSTATUSAUDIT_MESSAGETYPES_H
