// File: ATSAgentComms_MessageTypes.h
// Created: 12/04/2006 4:13:30 PM
// This file is automatically generated from 9999D02170001-TransActive_CORBA_Messages_Register.xls
// Reference: 9999-D02-17-0001, Version: 34.06, Status: Draft, Dated: 06 Apr 06
//
// * DO NOT MODIFY! *

#ifndef ATSAGENTCOMMS_MESSAGETYPES_H
#define ATSAGENTCOMMS_MESSAGETYPES_H

#include "MessageTypes.h"

namespace TA_Base_Core
{
	namespace ATSAgentComms
	{
		// Root context
		static MessageContext Context("GeneralComms", "ATSAgentComms", CommsMessage);

		// Message Types for context ATSAgentComms
		static const MessageType AtsPasUpdate(Context, "40010");
		static const MessageType AtsTisUpdate(Context, "40011");
		static const MessageType AtsTrainUpdate(Context, "40012");
		static const MessageType ECSUpdate(Context, "40013");
		static const MessageType WILDTrainUpdate(Context, "40014");
		static const MessageType AtsBasUpdate(Context, "40015");
		static const MessageType AtsPidsUpdate(Context, "40016");
	};
};

#endif // ATSAGENTCOMMS_MESSAGETYPES_H
