// File: AuthenticationAgentAudit_MessageTypes.h
// Created: 12/04/2006 4:13:30 PM
// This file is automatically generated from 9999D02170001-TransActive_CORBA_Messages_Register.xls
// Reference: 9999-D02-17-0001, Version: 34.06, Status: Draft, Dated: 06 Apr 06
//
// * DO NOT MODIFY! *

#ifndef AUTHENTICATIONAGENTAUDIT_MESSAGETYPES_H
#define AUTHENTICATIONAGENTAUDIT_MESSAGETYPES_H

#include "MessageTypes.h"

namespace TA_Base_Core
{
	namespace AuthenticationAgentAudit
	{
		// Root context
		static MessageContext Context("Audit", "AuthenticationAgentAudit", AuditMessage);

		// Message Types for context AuthenticationAgentAudit
		static const MessageType AuthenticationRequestDenied(Context, "30042");
		static const MessageType OverrideDenied(Context, "30043");
		static const MessageType OverrideEnded(Context, "30044");
		static const MessageType OverrideStarted(Context, "30045");
		static const MessageType PasswordChanged(Context, "30046");
		static const MessageType SessionEnded(Context, "30047");
		static const MessageType SessionStarted(Context, "30048");
	};
};

#endif // AUTHENTICATIONAGENTAUDIT_MESSAGETYPES_H
