// File: ConfigUpdate_MessageTypes.h
// Created: 12/04/2006 4:13:30 PM
// This file is automatically generated from 9999D02170001-TransActive_CORBA_Messages_Register.xls
// Reference: 9999-D02-17-0001, Version: 34.06, Status: Draft, Dated: 06 Apr 06
//
// * DO NOT MODIFY! *

#ifndef CONFIGUPDATE_MESSAGETYPES_H
#define CONFIGUPDATE_MESSAGETYPES_H

#include "MessageTypes.h"

namespace TA_Base_Core
{
	namespace ConfigUpdate
	{
		// Root context
		static MessageContext Context("Config", "ConfigUpdate", ConfigUpdateMessage);

		// Message Types for context ConfigUpdate
		static const MessageType CCTVEntity(Context, "20001");
		static const MessageType CCTVEntityOwner(Context, "20002");
		static const MessageType ConfigActionGroup(Context, "20003");
		static const MessageType ConfigAlarmPlanAssociation(Context, "20004");
		static const MessageType ConfigAlarmRule(Context, "20005");
		static const MessageType ConfigAlarmSeverity(Context, "20006");
		static const MessageType ConfigAlarmType(Context, "20007");
		static const MessageType ConfigApplication(Context, "20008");
		static const MessageType ConfigAtsBranchTrack(Context, "20009");
		static const MessageType ConfigAtsFixedBlockMap(Context, "20010");
		static const MessageType ConfigAtsMssZone(Context, "20011");
		static const MessageType ConfigAtsPlatform(Context, "20012");
		static const MessageType ConfigAtsPowerEntityMap(Context, "20013");
		static const MessageType ConfigAtsPsdEntityMap(Context, "20014");
		static const MessageType ConfigAtsTwpEntityMap(Context, "20015");
		static const MessageType ConfigEcMasterMode(Context, "20016");
		static const MessageType ConfigEcStationMode(Context, "20017");
		static const MessageType ConfigEcZone(Context, "20018");
		static const MessageType ConfigEntity(Context, "20019");
		static const MessageType ConfigEntityOwner(Context, "20020");
		static const MessageType ConfigEventColour(Context, "20021");
		static const MessageType ConfigEventPlanAssociation(Context, "20022");
		static const MessageType ConfigEventType(Context, "20023");
		static const MessageType ConfigGlobalParameter(Context, "20024");
		static const MessageType ConfigInterlocking(Context, "20025");
		static const MessageType ConfigITransportIor(Context, "20026");
		static const MessageType ConfigITSIGroup(Context, "20027");
		static const MessageType ConfigLocation(Context, "20028");
		static const MessageType ConfigMessageType(Context, "20029");
		static const MessageType ConfigMmsSchedule(Context, "20030");
		static const MessageType ConfigOperator(Context, "20031");
		static const MessageType ConfigPaAtsTriggeredBroadcast(Context, "20032");
		static const MessageType ConfigPaDvaMessage(Context, "20033");
		static const MessageType ConfigPaDvaVersion(Context, "20034");
		static const MessageType ConfigPaStation(Context, "20035");
		static const MessageType ConfigPaTrainDvaMessage(Context, "20036");
		static const MessageType ConfigPaZone(Context, "20037");
		static const MessageType ConfigPaZoneGroup(Context, "20038");
		static const MessageType ConfigPidGroupUpdate(Context, "20039");
		static const MessageType ConfigProfile(Context, "20040");
		static const MessageType ConfigProfileGroup(Context, "20041");
		static const MessageType ConfigRegion(Context, "20042");
		static const MessageType ConfigScadaDisplay(Context, "20043");
		static const MessageType ConfigSecurity(Context, "20044");
		static const MessageType ConfigSmsDevice(Context, "20045");
		static const MessageType ConfigSoundFile(Context, "20046");
		static const MessageType ConfigSubsystem(Context, "20047");
		static const MessageType ConfigSystemController(Context, "20048");
		static const MessageType ConfigSystemControllerGroup(Context, "20049");
		static const MessageType ConfigTisRatisDestination(Context, "20050");
		static const MessageType ConfigTisRatisTag(Context, "20051");
		static const MessageType ConfigTrend(Context, "20052");
		static const MessageType ConfigVideoStation(Context, "20053");
		static const MessageType ConfigVideoTriggeringEvent(Context, "20054");
		static const MessageType ConfigIncidentRights(Context, "20055");
        static const MessageType ConfigOPCTagAlias(Context, "20056");
        static const MessageType ConfigPaFasTriggeredBroadcast(Context, "20057");
	};
};

#endif // CONFIGUPDATE_MESSAGETYPES_H
