// File: IasAgentAudit_MessageTypes.h
// Created: 19/12/2005 3:25:09 PM
// This file is automatically generated from the message types register spreadsheet
//
// * DO NOT MODIFY! *

#ifndef IASAGENTAUDIT_MESSAGETYPES_H
#define IASAGENTAUDIT_MESSAGETYPES_H

#include "MessageTypes.h"

namespace TA_Base_Core
{
	namespace IasAgentAudit
	{
		// Root context
		static MessageContext Context("Audit", "IasAgentAudit", AuditMessage);

		// Message Types for context IasAgentAudit
		static const MessageType IASAlarmActive(Context, "30575");
		static const MessageType IASAlarmInactive(Context, "30576");
		static const MessageType IASSystemFault(Context, "30577");
		static const MessageType IASSystemNormal(Context, "30578");
	};
};

#endif // IASAGENTAUDIT_MESSAGETYPES_H
