// File: IncidentAlarms_MessageTypes.h
// Created: 1/11/2005 3:40:25 PM
// This file is automatically generated from the message types register spreadsheet
//
// * DO NOT MODIFY! *

#ifndef INCIDENTALARMS_MESSAGETYPES_H
#define INCIDENTALARMS_MESSAGETYPES_H

#include "MessageTypes.h"

namespace TA_Base_Core
{
	namespace IncidentAlarms
	{
		// Root context
		static MessageContext Context("Alarm", "IncidentAlarms", AlarmMessage);

		// Message Types for context IncidentAlarms
		static const MessageType IncidentDBAccessError(Context, "50232");
		static const MessageType IncidentRightsAgentAccessError(Context, "50233");
	};
};

#endif // INCIDENTALARMS_MESSAGETYPES_H
