// File: InspectorPanelAudit_MessageTypes.h
// Created: 12/04/2006 4:13:32 PM
// This file is automatically generated from 9999D02170001-TransActive_CORBA_Messages_Register.xls
// Reference: 9999-D02-17-0001, Version: 34.06, Status: Draft, Dated: 06 Apr 06
//
// * DO NOT MODIFY! *

#ifndef INSPECTORPANELAUDIT_MESSAGETYPES_H
#define INSPECTORPANELAUDIT_MESSAGETYPES_H

#include "MessageTypes.h"

namespace TA_Base_Core
{
	namespace InspectorPanelAudit
	{
		// Root context
		static MessageContext Context("Audit", "InspectorPanelAudit", AuditMessage);

		// Message Types for context InspectorPanelAudit
		static const MessageType DataNodeNotesUpdateRemove(Context, "30158");
		static const MessageType DataNodeTagAddRemove(Context, "30159");
		static const MessageType DataPointInhibitAddRemove(Context, "30160");
		static const MessageType DataPointOverrideAddRemove(Context, "30161");
	};
};

#endif // INSPECTORPANELAUDIT_MESSAGETYPES_H
