// File: MMSComms_MessageTypes.h
// Created: 5/07/2006 2:51:44 PM
// This file is automatically generated from 9999D02170001-TransActive_CORBA_Messages_Register.xls
// Reference: 9999-D02-17-0001, Version: 35.02, Status: Draft, Dated: 05 Jul 06
//
// * DO NOT MODIFY! *

#ifndef MMSCOMMS_MESSAGETYPES_H
#define MMSCOMMS_MESSAGETYPES_H

#include "MessageTypes.h"

namespace TA_Base_Core
{
	namespace MMSComms
	{
		// Root context
		static MessageContext Context("GeneralComms", "MMSComms", CommsMessage);

		// Message Types for context MMSComms
		static const MessageType NonPhysicalEntityMMSAlarmInhibitApplied(Context, "40194");
		static const MessageType NonPhysicalEntityMMSAlarmInhibitRemoved(Context, "40195");
	};
};

#endif // MMSCOMMS_MESSAGETYPES_H
