// File: OperatorAudit_MessageTypes.h
// Created: 12/04/2006 4:13:32 PM
// This file is automatically generated from 9999D02170001-TransActive_CORBA_Messages_Register.xls
// Reference: 9999-D02-17-0001, Version: 34.06, Status: Draft, Dated: 06 Apr 06
//
// * DO NOT MODIFY! *

#ifndef OPERATORAUDIT_MESSAGETYPES_H
#define OPERATORAUDIT_MESSAGETYPES_H

#include "MessageTypes.h"

namespace TA_Base_Core
{
	namespace OperatorAudit
	{
		// Root context
		static MessageContext Context("Audit", "OperatorAudit", AuditMessage);

		// Message Types for context OperatorAudit
		static const MessageType ApplicationChangeModeRequest(Context, "30001");
		static const MessageType ApplicationDebugLevelChange(Context, "30002");
		static const MessageType ApplicationStartRequest(Context, "30003");
		static const MessageType ApplicationStopRequest(Context, "30004");
		static const MessageType OperatorAdminLogIn(Context, "30005");
		static const MessageType OperatorAdminLogOut(Context, "30006");
		static const MessageType SystemControllerShutdown(Context, "30007");
		static const MessageType OperatorLoggedIn(Context, "30064");
		static const MessageType OperatorLoggedOut(Context, "30065");
		static const MessageType OperatorLoginFailure(Context, "30066");
		static const MessageType OperatorOverrideApplied(Context, "30067");
		static const MessageType OperatorOverrideRemoved(Context, "30068");
		static const MessageType OperatorProfileChange(Context, "30069");
	};
};

#endif // OPERATORAUDIT_MESSAGETYPES_H
