// File: PlanAgentAudit_MessageTypes.h
// Created: 12/04/2006 4:13:33 PM
// This file is automatically generated from 9999D02170001-TransActive_CORBA_Messages_Register.xls
// Reference: 9999-D02-17-0001, Version: 34.06, Status: Draft, Dated: 06 Apr 06
//
// * DO NOT MODIFY! *

#ifndef PLANAGENTAUDIT_MESSAGETYPES_H
#define PLANAGENTAUDIT_MESSAGETYPES_H

#include "MessageTypes.h"

namespace TA_Base_Core
{
	namespace PlanAgentAudit
	{
		// Root context
		static MessageContext Context("Audit", "PlanAgentAudit", AuditMessage);

		// Message Types for context PlanAgentAudit
		static const MessageType PlanApproval(Context, "30231");
		static const MessageType PlanAutoGRCBadLaunch(Context, "30232");
		static const MessageType PlanAutoGRCBadReturn(Context, "30233");
		static const MessageType PlanAutoGRCStarted(Context, "30234");
		static const MessageType PlanAutoGRCSuccessful(Context, "30235");
		static const MessageType PlanAutoGRCUnsuccessful(Context, "30236");
		static const MessageType PlanBRCStepBadLaunch(Context, "30237");
		static const MessageType PlanBRCStepBadReturn(Context, "30238");
		static const MessageType PlanBRCStepSuccessful(Context, "30239");
		static const MessageType PlanCategoryDelete(Context, "30240");
		static const MessageType PlanCategoryInsert(Context, "30241");
		static const MessageType PlanCategoryUpdate(Context, "30242");
		static const MessageType PlanComplete(Context, "30243");
		static const MessageType PlanCompletedWithFailedSteps(Context, "30244");
		static const MessageType PlanControlAcquire(Context, "30245");
		static const MessageType PlanCopy(Context, "30246");
		static const MessageType PlanDelete(Context, "30247");
		static const MessageType PlanEditLockAcquire(Context, "30248");
		static const MessageType PlanEditLockRelease(Context, "30249");
		static const MessageType PlanExecution(Context, "30250");
		static const MessageType PlanImportExport(Context, "30251");
		static const MessageType PlanInsert(Context, "30252");
		static const MessageType PlanManualGRCBadLaunch(Context, "30253");
		static const MessageType PlanManualGRCBadReturn(Context, "30254");
		static const MessageType PlanManualGRCStarted(Context, "30255");
		static const MessageType PlanManualGRCSuccessful(Context, "30256");
		static const MessageType PlanManualGRCUnsuccessful(Context, "30257");
		static const MessageType PlanMitsimInput(Context, "30258");
		static const MessageType PlanMove(Context, "30259");
		static const MessageType PlanOperatorsLog(Context, "30260");
		static const MessageType PlanPause(Context, "30261");
		static const MessageType PlanPending(Context, "30262");
		static const MessageType PlanResume(Context, "30263");
		static const MessageType PlanStepCustomisation(Context, "30264");
		static const MessageType PlanStop(Context, "30265");
		static const MessageType PlanUnapproval(Context, "30266");
		static const MessageType PlanUpdate(Context, "30267");
		static const MessageType PlanCopyFailure(Context, "30589");
		static const MessageType PlanApprovalFailure(Context, "30590");
		static const MessageType PlanDeleteFailure(Context, "30591");
		static const MessageType PlanPauseFailure(Context, "30592");
		static const MessageType PlanResumeFailure(Context, "30593");
		static const MessageType PlanStopFailure(Context, "30594");
		static const MessageType PlanUnApprovalFailure(Context, "30595");
		static const MessageType PlanStepExecFailure(Context, "30596");
	};
};

#endif // PLANAGENTAUDIT_MESSAGETYPES_H
