// File: SchedulingAudit_MessageTypes.h
// Created: 12/04/2006 4:13:33 PM
// This file is automatically generated from 9999D02170001-TransActive_CORBA_Messages_Register.xls
// Reference: 9999-D02-17-0001, Version: 34.06, Status: Draft, Dated: 06 Apr 06
//
// * DO NOT MODIFY! *

#ifndef SCHEDULINGAUDIT_MESSAGETYPES_H
#define SCHEDULINGAUDIT_MESSAGETYPES_H

#include "MessageTypes.h"

namespace TA_Base_Core
{
	namespace SchedulingAudit
	{
		// Root context
		static MessageContext Context("Audit", "SchedulingAudit", AuditMessage);

		// Message Types for context SchedulingAudit
		static const MessageType SchedulingAddJob(Context, "30345");
		static const MessageType SchedulingDeleteJob(Context, "30346");
		static const MessageType SchedulingDisableJob(Context, "30347");
		static const MessageType SchedulingEnableJob(Context, "30348");
		static const MessageType SchedulingJobCompleted(Context, "30349");
		static const MessageType SchedulingJobStarting(Context, "30350");
		static const MessageType SchedulingModifyJob(Context, "30351");
	};
};

#endif // SCHEDULINGAUDIT_MESSAGETYPES_H
