// File: SchedulingStateUpdate_MessageTypes.h
// Created: 12/04/2006 4:13:33 PM
// This file is automatically generated from 9999D02170001-TransActive_CORBA_Messages_Register.xls
// Reference: 9999-D02-17-0001, Version: 34.06, Status: Draft, Dated: 06 Apr 06
//
// * DO NOT MODIFY! *

#ifndef SCHEDULINGSTATEUPDATE_MESSAGETYPES_H
#define SCHEDULINGSTATEUPDATE_MESSAGETYPES_H

#include "MessageTypes.h"

namespace TA_Base_Core
{
	namespace SchedulingStateUpdate
	{
		// Root context
		static MessageContext Context("StateUpdate", "SchedulingStateUpdate", StateUpdateMessage);

		// Message Types for context SchedulingStateUpdate
		static const MessageType SchedulingStateUpdateBatchRequest(Context, "10075");
		static const MessageType SchedulingStateUpdateBatchUpdate(Context, "10076");
		static const MessageType SchedulingStateUpdateJobCompleted(Context, "10077");
		static const MessageType SchedulingStateUpdateJobStarting(Context, "10078");
	};
};

#endif // SCHEDULINGSTATEUPDATE_MESSAGETYPES_H
