// File: SystemAlarms_MessageTypes.h
// Created: 12/04/2006 4:13:33 PM
// This file is automatically generated from 9999D02170001-TransActive_CORBA_Messages_Register.xls
// Reference: 9999-D02-17-0001, Version: 34.06, Status: Draft, Dated: 06 Apr 06
//
// * DO NOT MODIFY! *

#ifndef SYSTEMALARMS_MESSAGETYPES_H
#define SYSTEMALARMS_MESSAGETYPES_H

#include "MessageTypes.h"

namespace TA_Base_Core
{
	namespace SystemAlarms
	{
		// Root context
		static MessageContext Context("Alarm", "SystemAlarms", AlarmMessage);

		// Message Types for context SystemAlarms
		static const MessageType DatabaseFailure(Context, "50085");
		static const MessageType FailoverOccurred(Context, "50086");
		static const MessageType GroupCommunicationsFailure(Context, "50087");
		static const MessageType MandatoryConfigInvalid(Context, "50088");
		static const MessageType MandatoryConfigMissing(Context, "50089");
		static const MessageType NoEntities(Context, "50090");
		static const MessageType OptionalConfigInvalid(Context, "50091");
		static const MessageType PeerCommunicationsFailure(Context, "50092");
		static const MessageType ProcessCommunicationsFailure(Context, "50093");
		static const MessageType ProcessFailure(Context, "50094");
	};
};

#endif // SYSTEMALARMS_MESSAGETYPES_H
