// File: SystemControllerComms_MessageTypes.h
// Created: 12/04/2006 4:13:34 PM
// This file is automatically generated from 9999D02170001-TransActive_CORBA_Messages_Register.xls
// Reference: 9999-D02-17-0001, Version: 34.06, Status: Draft, Dated: 06 Apr 06
//
// * DO NOT MODIFY! *

#ifndef SYSTEMCONTROLLERCOMMS_MESSAGETYPES_H
#define SYSTEMCONTROLLERCOMMS_MESSAGETYPES_H

#include "MessageTypes.h"

namespace TA_Base_Core
{
	namespace SystemControllerComms
	{
		// Root context
		static MessageContext Context("GeneralComms", "SystemControllerComms", CommsMessage);

		// Message Types for context SystemControllerComms
		static const MessageType SystemControllerGroupOffline(Context, "40127");
		static const MessageType SystemControllerGroupOnline(Context, "40128");
	};
};

#endif // SYSTEMCONTROLLERCOMMS_MESSAGETYPES_H
