// File: TrainStateUpdateContext_MessageTypes.h
// Created: 19/6/2006 PM 1:21:28
// This file is automatically generated from 9999D02170001-TransActive_CORBA_Messages_Register.xls
// Reference: 9999-D02-17-0001, Version: 34.10, Status: Draft, Dated: 24 May 06
//
// * DO NOT MODIFY! *

#ifndef TRAINSTATEUPDATECONTEXT_MESSAGETYPES_H
#define TRAINSTATEUPDATECONTEXT_MESSAGETYPES_H

#include "MessageTypes.h"

namespace TA_Base_Core
{
	namespace TrainStateUpdateContext
	{
		// Root context
		static MessageContext Context("StateUpdate", "TrainStateUpdateContext", StateUpdateMessage);

		// Message Types for context TrainStateUpdateContext
		static const MessageType TrainStateUpdate(Context, "10100");
	};
};

#endif // TRAINSTATEUPDATECONTEXT_MESSAGETYPES_H
