// File: VideoWallStateUpdates_MessageTypes.h
// Created: 12/04/2006 4:13:34 PM
// This file is automatically generated from 9999D02170001-TransActive_CORBA_Messages_Register.xls
// Reference: 9999-D02-17-0001, Version: 34.06, Status: Draft, Dated: 06 Apr 06
//
// * DO NOT MODIFY! *

#ifndef VIDEOWALLSTATEUPDATES_MESSAGETYPES_H
#define VIDEOWALLSTATEUPDATES_MESSAGETYPES_H

#include "MessageTypes.h"

namespace TA_Base_Core
{
	namespace VideoWallStateUpdates
	{
		// Root context
		static MessageContext Context("StateUpdate", "VideoWallStateUpdates", StateUpdateMessage);

		// Message Types for context VideoWallStateUpdates
		static const MessageType VideoWallProtocolStateUpdate(Context, "10091");
		static const MessageType VideoWallStateUpdate(Context, "10092");
		static const MessageType VideoWallStateUpdateRequest(Context, "10093");
	};
};

#endif // VIDEOWALLSTATEUPDATES_MESSAGETYPES_H
