// File: VisualStateUpdate_MessageTypes.h
// Created: 12/04/2006 4:13:34 PM
// This file is automatically generated from 9999D02170001-TransActive_CORBA_Messages_Register.xls
// Reference: 9999-D02-17-0001, Version: 34.06, Status: Draft, Dated: 06 Apr 06
//
// * DO NOT MODIFY! *

#ifndef VISUALSTATEUPDATE_MESSAGETYPES_H
#define VISUALSTATEUPDATE_MESSAGETYPES_H

#include "MessageTypes.h"

namespace TA_Base_Core
{
	namespace VisualStateUpdate
	{
		// Root context
		static MessageContext Context("StateUpdate", "VisualStateUpdate", StateUpdateMessage);

		// Message Types for context VisualStateUpdate
		static const MessageType VideoSwitchAgentStateUpdate(Context, "10089");
		static const MessageType VideoSwitchAgentStateUpdateRequest(Context, "10090");
	};
};

#endif // VISUALSTATEUPDATE_MESSAGETYPES_H
