// Assembly OPCTrendLib, Version 1.0.0.0

[assembly: System.Reflection.AssemblyVersion("1.1.0.0")]
[assembly: System.Reflection.AssemblyDescription("System Utility Library")]
//[assembly: System.Diagnostics.Debuggable(0x107)]
[assembly: System.Reflection.AssemblyCompany("ST Electronics Limited")]
[assembly: System.Reflection.AssemblyTitle("OPCTrendLib")]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyFileVersion("1.1.0.0")]
[assembly: System.Runtime.InteropServices.Guid("d56fda04-8fd0-4f2e-88b0-2408d0cf2e71")]
[assembly: System.Runtime.InteropServices.ComVisible(true)]
[assembly: System.Reflection.AssemblyTrademark("Copyright \x00a9 2006 Singapore Technologies Electronics Limited (Regn. No.: 196900084E )")]
[assembly: System.Reflection.AssemblyCopyright("Copyright \x00a9  2006")]
[assembly: System.Reflection.AssemblyProduct("OPCTrendLib")]
