// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __AlarmStoreCallbackCorbaDef_hh__
#define __AlarmStoreCallbackCorbaDef_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_AlarmStoreCallbackCorbaDef
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_AlarmStoreCallbackCorbaDef
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_AlarmStoreCallbackCorbaDef
#endif



#ifndef __GenericMessageCorbaDef_hh_EXTERNAL_GUARD__
#define __GenericMessageCorbaDef_hh_EXTERNAL_GUARD__
#include <GenericMessageCorbaDef.h>
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE TA_Base_Core

_CORBA_MODULE_BEG

#ifndef __TA__Base__Core_mIAlarmStoreCallbackCorbaDef__
#define __TA__Base__Core_mIAlarmStoreCallbackCorbaDef__

  class IAlarmStoreCallbackCorbaDef;
  class _objref_IAlarmStoreCallbackCorbaDef;
  class _impl_IAlarmStoreCallbackCorbaDef;
  
  typedef _objref_IAlarmStoreCallbackCorbaDef* IAlarmStoreCallbackCorbaDef_ptr;
  typedef IAlarmStoreCallbackCorbaDef_ptr IAlarmStoreCallbackCorbaDefRef;

  class IAlarmStoreCallbackCorbaDef_Helper {
  public:
    typedef IAlarmStoreCallbackCorbaDef_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_IAlarmStoreCallbackCorbaDef, IAlarmStoreCallbackCorbaDef_Helper> IAlarmStoreCallbackCorbaDef_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_IAlarmStoreCallbackCorbaDef,IAlarmStoreCallbackCorbaDef_Helper > IAlarmStoreCallbackCorbaDef_out;

#endif

  // interface IAlarmStoreCallbackCorbaDef
  class IAlarmStoreCallbackCorbaDef {
  public:
    // Declarations for this interface type.
    typedef IAlarmStoreCallbackCorbaDef_ptr _ptr_type;
    typedef IAlarmStoreCallbackCorbaDef_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_IAlarmStoreCallbackCorbaDef :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    void indexCleared();
    void itemInserted(const char* alarmID, ::CORBA::Long position);
    void itemMoved(const char* alarmID, ::CORBA::Long oldPosition, ::CORBA::Long newPosition);
    void itemDeleted(const char* alarmID, ::CORBA::Long position);
    ::CORBA::Boolean callbackCheck();

    inline _objref_IAlarmStoreCallbackCorbaDef()  { _PR_setobj(0); }  // nil
    _objref_IAlarmStoreCallbackCorbaDef(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_IAlarmStoreCallbackCorbaDef();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_IAlarmStoreCallbackCorbaDef(const _objref_IAlarmStoreCallbackCorbaDef&);
    _objref_IAlarmStoreCallbackCorbaDef& operator = (const _objref_IAlarmStoreCallbackCorbaDef&);
    // not implemented

    friend class IAlarmStoreCallbackCorbaDef;
  };

  class _pof_IAlarmStoreCallbackCorbaDef : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_IAlarmStoreCallbackCorbaDef() : _OMNI_NS(proxyObjectFactory)(IAlarmStoreCallbackCorbaDef::_PD_repoId) {}
    virtual ~_pof_IAlarmStoreCallbackCorbaDef();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_IAlarmStoreCallbackCorbaDef :
    public virtual omniServant
  {
  public:
    virtual ~_impl_IAlarmStoreCallbackCorbaDef();

    virtual void indexCleared() = 0;
    virtual void itemInserted(const char* alarmID, ::CORBA::Long position) = 0;
    virtual void itemMoved(const char* alarmID, ::CORBA::Long oldPosition, ::CORBA::Long newPosition) = 0;
    virtual void itemDeleted(const char* alarmID, ::CORBA::Long position) = 0;
    virtual ::CORBA::Boolean callbackCheck() = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_IAlarmStoreCallbackCorbaDef;

_CORBA_MODULE_END



_CORBA_MODULE POA_TA_Base_Core
_CORBA_MODULE_BEG

  class IAlarmStoreCallbackCorbaDef :
    public virtual TA_Base_Core::_impl_IAlarmStoreCallbackCorbaDef,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~IAlarmStoreCallbackCorbaDef();

    inline ::TA_Base_Core::IAlarmStoreCallbackCorbaDef_ptr _this() {
      return (::TA_Base_Core::IAlarmStoreCallbackCorbaDef_ptr) _do_this(::TA_Base_Core::IAlarmStoreCallbackCorbaDef::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_TA_Base_Core
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, TA_Base_Core::IAlarmStoreCallbackCorbaDef_ptr _s);
void operator<<=(::CORBA::Any& _a, TA_Base_Core::IAlarmStoreCallbackCorbaDef_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, TA_Base_Core::IAlarmStoreCallbackCorbaDef_ptr& _s);



inline void
TA_Base_Core::IAlarmStoreCallbackCorbaDef::_marshalObjRef(::TA_Base_Core::IAlarmStoreCallbackCorbaDef_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_AlarmStoreCallbackCorbaDef
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_AlarmStoreCallbackCorbaDef
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_AlarmStoreCallbackCorbaDef
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_AlarmStoreCallbackCorbaDef
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_AlarmStoreCallbackCorbaDef
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_AlarmStoreCallbackCorbaDef
#endif

#endif  // __AlarmStoreCallbackCorbaDef_hh__

