PROJ_ROOT_DIR = ../../../../..
PROJ_NAME = sqlgen
PROJ_CODE_DIR = transactive/app/dbsynch/sqlgen/
PROJ_SRC_DIR = ./src
PROJ_SOURCE = sqlgen.cpp \
		ISystemListNodeImp.cpp \
		ISystemLIstNodeDataImp.cpp \
		ISystemListImp.cpp \
		CAllDataClass.cpp \
		main.cpp

PROJ_TYPE = exe

PROJ_OBJ_DIR = ./bin
PROJ_OUT_DIR = ./bin
PROJ_INC_DIR = ./src

PROJ_CFLAGS = -DTA_ASSERT_LOG=1




##############################################################
# The main include file that has all the wiz bang stuff for neato compiling
##############################################################

include $(PROJ_ROOT_DIR)/code/tools/build/CommonMakefile.mak
install:
	#Do Nothing

